### ISSUE TITLE
[Suggestion] Avoid printing IP address or provide control flag

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AlexFlipnote/neofetch-win#14]
The IP address can be sensitive at times, if possible please provide a flag or dont print IP address. 
Another suggestion would be to have flags to skip/include specific information.

**Comment by AlexFlipnote** [comment]
Done, I added `--ignore` argument, as well as improved `--colour` and `--artcolour` parsing.
Update to 1.1.3 to experience this new update, thank you for your lovely suggestion 🥰
