### ISSUE TITLE
No longer works on WIndows 11 Dev Insider

### ISSUE THREAD

**Issue by SimPilotAdamT** [AlexFlipnote/neofetch-win#18]
`neofetch-win` relies on `wmic` in order to get the system info. Now, however, `wmic` has been removed from the dev branch of Windows 11, rendering `neofetch-win` unusable in the dev branch, and potentially unusable in future versions. How can this be fixed?

**Comment by wasi-master** [comment]
For reference, it has been removed from Windows 11 build 22483 and higher

**Comment by SimPilotAdamT** [comment]
Did some research, and it looks like we can use [get-ciminstance](https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/get-ciminstance?view=powershell-7.2) as an alternative to WMIC, but it needs PowerShell at least at version 7.2.

**Comment by AlexFlipnote** [comment]
Sorry for the delay, working on a fix right now
![](https://i.alexflipnote.dev/7NCsZ2F.png)

**Comment by AlexFlipnote** [comment]
This has been fixed, be sure to update your pip package 💖
