### ISSUE TITLE
Doesn't detect 3080 but does detect Disabled DisplayLink device?

### ISSUE THREAD

**Issue by SimPilotAdamT** [AlexFlipnote/neofetch-win#21]
I have my system with an RTX 3080 (as shown in the screenshot below). It is connected to a thunderbolt dock with support for DisplayLink, but I have disabled the DisplayLink functionality of the device. Still, every time I try to run `neofetch-win` on the latest version, it only shows the *disabled* DIsplayLink device.

Any ideas?

![image](https://user-images.githubusercontent.com/71192298/170120013-83df6e5f-c091-443f-8121-2de4ae6cf22c.png)

**Comment by AlexFlipnote** [comment]
Any reason you closed this issue?

**Comment by SimPilotAdamT** [comment]
> Any reason you closed this issue?

I did *not* mean to close it. Didn't notice until I looked again just now lol

**Comment by kernel-dev** [comment]
Hi, @SimPilotAdamT

Would you be able to run the following command for me in PowerShell?

```ps1
Get-WmiObject -Class Win32_VideoController | Select-Object -Property *
```

Copy the output and send it here, please.

**Comment by AlexFlipnote** [comment]
This should be fixed with a later update that was done
