### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by StupidMurderDroneFanThatUsesArchBtw** [AlexFlipnote/neofetch-win#27]
![image_2024-08-07_142534418](https://github.com/user-attachments/assets/5ae58faf-f73e-4def-a547-83706cd7f04b)

**Comment by AlexFlipnote** [comment]
What Python version are you using?

**Comment by StupidMurderDroneFanThatUsesArchBtw** [comment]
> What Python version are you using?

Python 3.12.4

**Comment by AlexFlipnote** [comment]
What's the version of psutil you have?
```
C:\Users\AlexFlipnote>python --version
Python 3.12.4
```
```py
>>> import psutil
>>> psutil.__version__
'6.0.0'
```
Tested with my local machine and 6.0.0 works on my end at least, which seems to be latest version.

**Comment by StupidMurderDroneFanThatUsesArchBtw** [comment]
> What's the version of psutil you have?
> 
> ```
> C:\Users\AlexFlipnote>python --version
> Python 3.12.4
> ```
> 
> ```python
> >>> import psutil
> >>> psutil.__version__
> '6.0.0'
> ```
> 
> Tested with my local machine and 6.0.0 works on my end at least, which seems to be latest version.

it says i have psutil installed but when i try to use anything psutil related it says i dont have psutil

**Comment by StupidMurderDroneFanThatUsesArchBtw** [comment]
![image_2024-08-07_174925735](https://github.com/user-attachments/assets/fc318187-a458-4fbb-ba8c-5c2a73299434)

**Comment by StupidMurderDroneFanThatUsesArchBtw** [comment]
![Uploading image_2024-08-07_175119569.png…]()

**Comment by StupidMurderDroneFanThatUsesArchBtw** [comment]
![image_2024-08-07_175133776](https://github.com/user-attachments/assets/a08666b7-a2d1-495a-9b9b-790e173fcb76)

**Comment by AlexFlipnote** [comment]
It feels a bit out of scope for neofetch, since with the same settings that you have but for my own machine, it works. I'd recommend checking your Windows to see if psutil simply has no access to get DLL, maybe if it could be that your Python and Windows are in two different partitions, etc.

Could also try `pip install psutil==5.9.3` and see if lower version works for your case

**Comment by StupidMurderDroneFanThatUsesArchBtw** [comment]
> pip install psutil==5.9.3

Collecting psutil==5.9.3
  Downloading psutil-5.9.3.tar.gz (483 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psutil
  Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\psutil
      copying psutil\_common.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_compat.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_psaix.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_psosx.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_psposix.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-312\psutil
      copying psutil\__init__.py -> build\lib.win-amd64-cpython-312\psutil
      creating build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-312\psutil\tests
      copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-312\psutil\tests
      running build_ext
      building 'psutil._psutil_windows' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (psutil)

**Comment by StupidMurderDroneFanThatUsesArchBtw** [comment]
I ALREADY HAVE C++ 14.0.85 INSTALLED

**Comment by AlexFlipnote** [comment]
The error says you apparently do not, so there is not much i can say or do. Essentially, try different versions of psutil and see if it can help, i will look into seeing if the tool is required on later updates
