### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by HelloGwkki** [AlexFlipnote/neofetch-win#7]
#### I running Neofetch-win Has Some Error.
`Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Scripts\neofetch-script.py", line 11, in <module>
    load_entry_point('neofetch-win==1.0.9', 'console_scripts', 'neofetch')()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\main.py", line 59, in main
    shell()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\main.py", line 54, in shell
    print(nf.pretty_print(), file=nf.stream)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\neofetch.py", line 209, in pretty_print
    f"{self.colourize('OS')}: {self.os}",
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\neofetch.py", line 121, in os
    lines = self.wmic("wmic os get Caption")
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\neofetch_win\neofetch.py", line 75, in wmic
    output = stdout.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 51: invalid continuation byte`
????:dog:

**Comment by AlexFlipnote** [comment]
Hi there, sorry for the late response.
I will have a look on why this happens when I get the time.
Do you happen to use any UTF-8 characters in your username to your PC or anything else, that could possible trigger a UTF-8 codec error?

Would be appreciated if you could reply with anything you know of that could output special characters, here's all the entry points it will find from your PC. 

![Image](https://i.alexflipnote.dev/4az4zam.png)

**Comment by HelloGwkki** [comment]
Well, yes.
Hello, I'm from China, so my computer is in Chinese.
Also, I would like to thank you very much for your reply to my email.
This email is translated by translation software. There may be some grammar problems. I hope you can understand it.
Also, I will test on the Chinese version of Ubuntu. If there is any problem, I will reply.
additional
Processor: AMD Athlon (TM) II x2 250u processor 1.60 GHz
Operating system: Windows 7 Service Pack 1 x86
I hope these parameters are useful
--MiaoSamaCoder






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AlexFlipnote"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 晚上10:21
收件人:&nbsp;"AlexFlipnote/neofetch-win"<neofetch-win@noreply.github.com&gt;;
抄送:&nbsp;"Miao Sama"<ddos_ping@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AlexFlipnote/neofetch-win] ERROR (#7)




Hi there, sorry for the late response.
 I will have a look on why this happens when I get the time.
 Do you happen to use any UTF-8 characters in your username to your PC or anything else, that could possible trigger a UTF-8 codec error?
 
Would be appreciated if you could reply with anything you know of that could output special characters, here's all the entry points it will find from your PC.

**Comment by HelloGwkki** [comment]
> 嗨，您好，很抱歉回复迟到。
> 如果有时间，我将看看为什么会发生这种情况。
> 您是否在PC或其他任何用户名中使用了UTF-8字符，可能会触发UTF-8编解码器错误？
> 
> 如果您可以回答任何已知的可以输出特殊字符的内容，将不胜感激，这是您可以从PC上找到的所有切入点。
> 
> ![图片](https://camo.githubusercontent.com/54ae77e9fd4a11cf531200536f01e4af115e157e/68747470733a2f2f692e616c6578666c69706e6f74652e6465762f34617a347a616d2e706e67)

Sorry, I don't know. But Chinese should be utf-8, but I didn't use Chinese in any username.

**Comment by MiaoSamaCoder** [comment]
:grimacing:

**Comment by AlexFlipnote** [comment]
Should be fixed in 1.1.0 (1a94866), hopefully it works ❤️

**Comment by HelloGwkki** [comment]
okay:heart:

**Comment by AlexFlipnote** [comment]
Closing issue as it's fixed, if the problem appears again, don't hesitate to make a new issue.

**Comment by MiaoSamaCoder** [comment]
ohhhhh...new error.
